env:
  JULIA_NUM_THREADS: auto
  QUANTUMSAVORY_PLOT_TEST: true

secrets:
  - CODECOV_TOKEN

steps:
  - label: "CI Buildkite"
    plugins:
      - QuantumSavory/julia#v1.14:
          version: "1"
      - QuantumSavory/julia-xvfb#v1.2:
      - JuliaCI/julia-test#v1: ~
      - JuliaCI/julia-coverage#v1: ~
